<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lecture extends Model
{
    use HasFactory;

    protected $fillable = [
        'id','title','description','content','course_id','created_at','updated_at'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($lecture) {
            foreach ($lecture->documents as $document) {
                $document->delete();
            }
        });
    }

    public function course(){
        return $this->belongsTo(Course::class);
    }

    public function documents()
    {
        return $this->morphMany(Document::class, 'documentable');
    }
}
